Reorganize chezmoi scripts and consolidate SSH remote setup
- Move SSH remote change logic from dedicated script to misc script
- Reorder script execution priorities by renaming numeric prefixes
- Change package installation from before hook to after hook
- Move Darwin preferences to earlier execution order

diff --git a/chezmoi/.chezmoiscripts/run_once_after_99-misc.sh.tmpl b/chezmoi/.chezmoiscripts/run_once_after_99-misc.sh.tmpl
--- a/chezmoi/.chezmoiscripts/run_once_after_99-misc.sh.tmpl
+++ b/chezmoi/.chezmoiscripts/run_once_after_99-misc.sh.tmpl
@@ -14,3 +14,17 @@ killall Dock
 echo "Install TX-02 Fonts"
 op document get "TX-02 Fonts" --force -o /tmp/tx02.tar
 tar xf /tmp/tx02.tar -C ~/Library/Fonts/
+
+echo "Change the Git remote from HTTP to SSH"
+cd {{ .chezmoi.sourceDir }} || exit 1
+
+# Change the Git remote from HTTP to SSH
+git remote set-url origin git@github.com:$(git remote get-url origin | sed -e 's/https:\/\/github.com\///')
+
+# Check if the command was successful
+if [ $? -eq 0 ]; then
+    echo "Successfully changed Git remote to SSH."
+else
+    echo "Failed to change Git remote to SSH."
+    exit 1
+fi
